

// #define VAL_ALLOCATOR_DONT_RECLAIM
#define MICRO_PARTITIONER_MAX_PART_SIZE 99999

// #define REPCUT_WEIGHT_BALANCE_SMEM_USAGE
#define REPCUT_WEIGHT_BALANCE_SIM_SPEED

#define REPCUT_PART_SIZE_RATIO_START 0.11
#define REPCUT_PART_SIZE_RATIO_STEP 0.05
#define REPCUT_PART_SIZE_RATIO_MAX 1.0
#define REPCUT_AUTO_PART_CNT_GPU_SM_MARGIN 0.9