

// #define VAL_ALLOCATOR_DONT_RECLAIM
#define MICRO_PARTITIONER_MAX_PART_SIZE 99999

// Tweak between 0 to 1
#define PARTITIONING_MANAGER_CUT_TARGET 0.6f
#define PARTITIONING_MANAGER_MAX_WEIGHT_R0 200000
#define PARTITIONING_MANAGER_PREFERRED_WEIGHT_R0 150000
#define PARTITIONING_MANAGER_MAX_WEIGHT_RATIO_R1 1.3
#define PARTITIONING_MANAGER_MAX_REPARTITION_R0 0
#define PARTITIONING_MANAGER_MAX_REPARTITION_R1 0
// #define PARTITIONING_MANAGER_MAX_WEIGHT_R1 500000
// #define PARTITIONING_MANAGER_PREFERRED_WEIGHT_R1 300000



// #define PARTITIONING_MANAGER_CUT_TARGET 0.4f
// #define PARTITIONING_MANAGER_MAX_WEIGHT_R0 120000
// #define PARTITIONING_MANAGER_PREFERRED_WEIGHT_R0 100000
// #define PARTITIONING_MANAGER_MAX_WEIGHT_R1 400000
// #define PARTITIONING_MANAGER_PREFERRED_WEIGHT_R1 300000

