
#pragma once

#include "circt/Dialect/HW/HWOps.h"
#include "mlir/IR/BuiltinAttributes.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Operation.h"

#include "mlir/Bytecode/BytecodeOpInterface.h"
#include "mlir/Pass/AnalysisManager.h"

#include "mlir/Support/LLVM.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/Support/Debug.h"

#include "circt/Dialect/HW/HWDialect.h"

#include <cstdint>
#include <optional>

#include "toucan/ToucanAttributes.h"
#include "toucan/ToucanDialect.h"
#include "toucan/ToucanOps.h"

#include <boost/graph/adjacency_list.hpp>

#include <unordered_map>

namespace toucan {

  enum class CGToucanOPName {
    ConstDecl,
    LUT,
    VecRead,
    Print,
    Stop,
    RegRead,
    RegWrite,
    MemRead,
    MemWrite,
    // Constant,
    // ConstVec
  };

  struct PartitioningGraphNodeProperty {
    public:
    // LUTOpName opName;
    mlir::Operation *op;
    // weight is actually number of ops in this node
    uint32_t weight;
    
    CGToucanOPName toucanOpName;
  };

  // Note: use boost::vecS (std::vector) to ensure vertex_descriptor is integer and also incremental

  typedef boost::adjacency_list<boost::vecS, boost::vecS, boost::bidirectionalS, PartitioningGraphNodeProperty, boost::no_property, boost::no_property, boost::listS> PartitioningGraph;



  struct CGValueMetaInfo {
    bool isConst;
    // value is valid if isConst
    uint8_t value;
    mlir::Operation *definingOp;
  };


  struct CGLUTOpMetaInfo {
    uint8_t lutId;
    // assert size == 3
    uint32_t op1;
    uint32_t op2;
    uint32_t op3;

    uint32_t result;
  };
  struct CGVectorReadOpMetaInfo {
    uint32_t vecBase;
    uint32_t vecLength;
    
    // max addr width: 16
    uint32_t addr1;
    uint32_t addr2;
    uint32_t addr3;
    uint32_t addr4;
    uint32_t outRangeValue;
    // Note: This offset is a static value!!!!
    uint16_t offset;
  };

  struct CGPrintOpMetaInfo {
    uint32_t en;
    uint32_t msg;
  };
  struct CGStopOpMetaInfo {
    uint32_t en;
  };
  struct CGRegReadOpMetaInfo {
    // reg: index in global regPool
    uint32_t reg;
    uint32_t result;
  };
  struct CGRegWriteOpMetaInfo {
    uint32_t reg;
    uint32_t dat;
  };
  struct CGMemReadOpMetaInfo {
    bool hasMultipleWriter;
    // Should do boundary check
    uint32_t memDepth;
    
    uint64_t memBase;

    // max addr width: 32
    uint32_t addr1;
    uint32_t addr2;
    uint32_t addr3;
    uint32_t addr4;
    uint32_t addr5;
    uint32_t addr6;
    uint32_t addr7;
    uint32_t addr8;

    uint32_t result;
  };
  struct CGMemWriteOpMetaInfo {
    bool hasMultipleWriter;
    // should do boundary check
    uint32_t memDepth;

    uint64_t memBase;

    // max addr width: 32
    uint32_t addr1;
    uint32_t addr2;
    uint32_t addr3;
    uint32_t addr4;
    uint32_t addr5;
    uint32_t addr6;
    uint32_t addr7;
    uint32_t addr8;

    uint32_t dat;
  };


  struct CGOpMetaInfo {
    CGToucanOPName opName;
    
    union {
      // top level
      CGMemReadOpMetaInfo memRead;
      CGRegReadOpMetaInfo regRead;

      // middle levels, exec
      CGLUTOpMetaInfo lut;
      CGVectorReadOpMetaInfo vec;

      // last level
      CGMemWriteOpMetaInfo memWrite;
      CGRegWriteOpMetaInfo regWrite;
      CGPrintOpMetaInfo print;
      CGStopOpMetaInfo stop;
    };

    std::optional<mlir::StringRef> namehint;
    uint32_t fragment_id;

    mlir::Operation *op;
  };

  struct CGRegMetaInfo {
    std::optional<mlir::StringRef> namehint;
    uint32_t bitWidth;
    uint32_t fragment_id;
    bool isPadding;
  };

  struct CGMemMetaInfo {
    std::optional<mlir::StringRef> namehint;
    uint32_t bitWidth;
    uint64_t memDepth;
    uint32_t fragment_id;
    bool hasMultipleWriter;
    uint64_t memBase;
  };

  // Information needed for code gen, each level
  struct CGPartitionMetaInfo {
    // Values generated by each layer. Will also be used as input of next level
    mlir::SmallVector<CGValueMetaInfo> valuePool;
    // Beginning N values are constant
    uint32_t numConstsInValuePool;
    // Operator pool in each level
    mlir::SmallVector<mlir::SmallVector<CGOpMetaInfo>> opPool;
    mlir::DenseMap<mlir::Operation*, uint32_t> opToResultValueId;

  };

  struct CGInfo {
    // Global register region. 
    mlir::SmallVector<CGRegMetaInfo> regPool;
    // Memories
    mlir::SmallVector<CGMemMetaInfo> memPool;
    uint64_t totalMemSize;

    mlir::SmallVector<std::string> printStrings;

    // debug info
    // name -> (start pos, bit width)
    std::unordered_map<std::string, std::tuple<uint32_t, uint32_t>> regDebugInfo;
    std::unordered_map<std::string, std::tuple<uint32_t, uint32_t>> signalDebugInfo;
    // name -> (start pos, bit width, length)
    std::unordered_map<std::string, std::tuple<uint32_t, uint32_t, uint32_t>> memDebugInfo;

    // For developing purpose
    mlir::DenseMap<mlir::TypedValue<toucan::RegType>, uint32_t> toucanRegToId;
    mlir::DenseMap<mlir::TypedValue<toucan::MemType>, uint32_t> toucanMemToId;

    mlir::SmallVector<CGPartitionMetaInfo> partitionInfo;
  };

  class IsLegalToucan4B {

  public:
    bool isToucanOnly;
    bool is4BOnly;
    bool isLegalToucan4B;

    IsLegalToucan4B(mlir::Operation *op);
  private:
    uint32_t chunkSize = 20000;
  };



  class DesignGraph {
  public:
    PartitioningGraph g;
    // mlir::DenseSet<uint32_t> sinkVtxs;
    // mlir::DenseSet<mlir::Operation*> constDeclVtxs;
    mlir::DenseMap<mlir::Operation*, uint32_t> opToId;

    // mlir::SmallVector<toucan::ConstantOp*> constOps;
    // mlir::SmallVector<toucan::DefConstVectorOp*> constVecOps;
    
    DesignGraph(mlir::Operation *op, mlir::AnalysisManager &am);

    static bool opShouldRemoveInGraph(mlir::Operation *op);
  private:

  
  };


  class PartitionerNCodeGenBase {
  public:
    mlir::SmallVector<mlir::BitVector> partitions;
    mlir::SmallVector<uint32_t> vtxIdToPartId;
    // partition i -> level j -> elem k
    mlir::SmallVector<mlir::SmallVector<mlir::SmallVector<uint32_t>>> partLevels;

    CGInfo codeGenInfo;

    void levelizePartitions(DesignGraph &graph);

    void generateMemoryLayout(DesignGraph &graph, uint32_t partitionRegPaddingSpace = 32, uint32_t memPaddingSpace = 32);

  private:

    void collectConstant(DesignGraph &graph, CGPartitionMetaInfo &partInfo, uint32_t partId);
    // void collectPrintMsgs(DesignGraph &graph);
    void generateRegMemLayout(DesignGraph &graph, uint32_t partitionRegPaddingSpace = 32, uint32_t memPaddingSpace = 32);
  };


  class NaivePartitioner: PartitionerNCodeGenBase {
    public:
    NaivePartitioner(mlir::Operation *op, mlir::AnalysisManager &am);
  };

  class RepCutPartitioner: PartitionerNCodeGenBase {
    public:
    RepCutPartitioner(mlir::Operation *op, mlir::AnalysisManager &am);
  };

}
